INSERT INTO PIER (NAME, SPOTS) VALUES ("Pier A", 3);
INSERT INTO PIER (NAME, SPOTS) VALUES ("Pier B", 2);
INSERT INTO PIER (NAME, SPOTS) VALUES ("Pier C", 1);
INSERT INTO PIER (NAME, SPOTS) VALUES ("Pier D", 5);
INSERT INTO PIER (NAME, SPOTS) VALUES ("Pier E", 4);