INSERT INTO SHIP(NAME,WEIGHT, COMPANY_ID, PIER_ID) VALUE ('ITCHING GREEN', 1986.88, 1, 3);
INSERT INTO SHIP(NAME,WEIGHT, COMPANY_ID, PIER_ID) VALUE ('Test Ship1', 1886.88, 1, 1);
INSERT INTO SHIP(NAME,WEIGHT, COMPANY_ID, PIER_ID) VALUE ('Test Ship2', 1886.88, 1, 1);
INSERT INTO SHIP(NAME,WEIGHT, COMPANY_ID, PIER_ID) VALUE ('Test Ship3', 1886.88, 1, 1);
INSERT INTO SHIP(NAME,WEIGHT, COMPANY_ID, PIER_ID) VALUE ('Test Ship4', 1886.88, 2, 1);
INSERT INTO SHIP(NAME,WEIGHT, COMPANY_ID, PIER_ID) VALUE ('Test Ship5', 1886.88, 2, 1);