CREATE TABLE STAY (
 ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 SHIP_ID BIGINT,
 ENTRY TIMESTAMP,
 `EXIT` TIMESTAMP,
 `VALUE` DECIMAL(10,2)
)engine=InnoDB;

ALTER TABLE STAY ADD CONSTRAINT FK_SHIP_STAY FOREIGN KEY(SHIP_ID) REFERENCES SHIP (ID);